# 1.Business Understanding

Given an online review, determine whether the sentiment is Positive, Negative, or Neutral.

# 2.Data Collection

In [1]:
import pandas as pd

data = {"review":["I REALLY loved this Phone!!! Best camera ever 😍😍 Visit https://bit.ly/x",
                    "Worst phone EVER!!! 😡😡 Battery drains in 2 hours... Don't buy!!!",
                    "Camera quality is AMAZING!!! 😊😊 Very happy with purchase. Visit www.shop.com",
                     "The phone is okay... Nothing special 🤔" ],
        "sentiment":["Positive",
                     "Negative",
                     "Positive",
                     "Neutral"]}

df = pd.DataFrame(data)
df

                                              review sentiment
0  I REALLY loved this Phone!!! Best camera ever ...  Positive
1  Worst phone EVER!!! 😡😡 Battery drains in 2 hou...  Negative
2  Camera quality is AMAZING!!! 😊😊 Very happy wit...  Positive
3             The phone is okay... Nothing special 🤔   Neutral

# 3.Data Understanding

In [2]:
df.head()

                                              review sentiment
0  I REALLY loved this Phone!!! Best camera ever ...  Positive
1  Worst phone EVER!!! 😡😡 Battery drains in 2 hou...  Negative
2  Camera quality is AMAZING!!! 😊😊 Very happy wit...  Positive
3             The phone is okay... Nothing special 🤔   Neutral

In [3]:
df.shape

(4, 2)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     4 non-null      object
 1   sentiment  4 non-null      object
dtypes: object(2)
memory usage: 192.0+ bytes

# 4.Data Preparation

In [ ]:
pip install nltk

In [ ]:
import nltk

nltk.download('stopwords')   # for removing common word
nltk.download('wordnet')     # Lemmatization
nltk.download('omw-1.4')     #Supporting Wordnet language resources

In [6]:
import re
import string
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [7]:
stop_words = set(stopwords.words("english"))  #This gets a list of common English stopwords from NLTK.
lemmatizer = WordNetLemmatizer()  # This creates a lemmatizer object from NLTK.The lemmatizer converts words into their base/dictionary form.

In [8]:
# Preprocessing functon

def preprocess(text):
    text = text.lower()
    text = re.sub(r"http\S+", "",text)
    text = re.sub(r"[^\w\s]", "", text)
    text = text.translate(str.maketrans('', '',string.punctuation))
    tokens = text.split()
    tokens = [word for word in tokens if word not in stop_words]
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return " ".join(tokens)

df["clean_review"] = df["review"].apply(preprocess)
print(df[["review","clean_review"]])

                                              review  \
0  I REALLY loved this Phone!!! Best camera ever ...
1  Worst phone EVER!!! 😡😡 Battery drains in 2 hou...
2  Camera quality is AMAZING!!! 😊😊 Very happy wit...
3             The phone is okay... Nothing special 🤔

                                        clean_review
0          really loved phone best camera ever visit
1     worst phone ever battery drain 2 hour dont buy
2  camera quality amazing happy purchase visit ww...
3                         phone okay nothing special

# 4.1 Bag Model

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
x_bow = cv.fit_transform(df["clean_review"])
bow_df = pd.DataFrame(x_bow.toarray(),columns=cv.get_feature_names_out())
bow_df

,amazing,battery,best,buy,camera,dont,drain,ever,happy,hour,...,nothing,okay,phone,purchase,quality,really,special,visit,worst,wwwshopcom
0,0,0,1,0,1,0,0,1,0,0,...,0,0,1,0,0,1,0,1,0,0
1,0,1,0,1,0,1,1,1,0,1,...,0,0,1,0,0,0,0,0,1,0
2,1,0,0,0,1,0,0,0,1,0,...,0,0,0,1,1,0,0,1,0,1
3,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,1,0,0,0

# 4.2 TF-IDF Vectorization

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(ngram_range=(1,2))
X_tfidf = tfidf.fit_transform(df["clean_review"])
tfidf_df = pd.DataFrame(X_tfidf.toarray(),columns=tfidf.get_feature_names_out())
tfidf_df.round(2)

,amazing,amazing happy,battery,battery drain,best,best camera,buy,camera,camera ever,camera quality,...,quality,quality amazing,really,really loved,special,visit,visit wwwshopcom,worst,worst phone,wwwshopcom
0,0.00,0.00,0.00,0.00,0.3,0.3,0.00,0.23,0.3,0.00,...,0.00,0.00,0.3,0.3,0.0,0.23,0.00,0.00,0.00,0.00
1,0.00,0.00,0.27,0.27,0.0,0.0,0.27,0.00,0.0,0.00,...,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.27,0.27,0.00
2,0.29,0.29,0.00,0.00,0.0,0.0,0.00,0.23,0.0,0.29,...,0.29,0.29,0.0,0.0,0.0,0.23,0.29,0.00,0.00,0.29
3,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.00,...,0.00,0.00,0.0,0.0,0.4,0.00,0.00,0.00,0.00,0.00

# 5.Model Building || 6.Model Training

In [11]:
from sklearn.linear_model import LogisticRegression
X= X_tfidf
y = df["sentiment"]
model = LogisticRegression()
model.fit(X,y)

LogisticRegression()

# 7.Model Testing|8.Model Prediction

In [12]:
new_review = ["Good Camera and battery"]
new_review_clean = [preprocess(text) for text in new_review]
new_review_tfidf = tfidf.transform(new_review_clean)
prediction = model.predict(new_review_tfidf)
print(prediction)

['Positive']

# Applying Word2Vec

## 1.Install Word2Vec Library

In [ ]:
!pip install gensim

## 2.Importing Word2Vec

In [13]:
from gensim.models import Word2Vec
import numpy as np

## 3.Data Preparation

In [14]:
sentences =[review.split() for review in df["clean_review"]]
sentences

[['really', 'loved', 'phone', 'best', 'camera', 'ever', 'visit'],
 ['worst', 'phone', 'ever', 'battery', 'drain', '2', 'hour', 'dont', 'buy'],
 ['camera', 'quality', 'amazing', 'happy', 'purchase', 'visit', 'wwwshopcom'],
 ['phone', 'okay', 'nothing', 'special']]

### 3.1 Training the Word2Vec Model

In [17]:
word2vec_model = Word2Vec(sentences=sentences,vector_size=100,window=5,min_count=1,workers=4,sg=1)

word2vec_model

In [18]:
word2vec_model.wv["phone"]

array([-5.3622725e-04,  2.3643136e-04,  5.1033497e-03,  9.0092728e-03,
       -9.3029495e-03, -7.1168090e-03,  6.4588725e-03,  8.9729885e-03,
       -5.0154282e-03, -3.7633716e-03,  7.3805046e-03, -1.5334714e-03,
       -4.5366134e-03,  6.5540518e-03, -4.8601604e-03, -1.8160177e-03,
        2.8765798e-03,  9.9187379e-04, -8.2852151e-03, -9.4488179e-03,
        7.3117660e-03,  5.0702621e-03,  6.7576934e-03,  7.6286553e-04,
        6.3508903e-03, -3.4053659e-03, -9.4640139e-04,  5.7685734e-03,
       -7.5216377e-03, -3.9361035e-03, -7.5115822e-03, -9.3004224e-04,
        9.5381187e-03, -7.3191668e-03, -2.3337686e-03, -1.9377411e-03,
        8.0774371e-03, -5.9308959e-03,  4.5162440e-05, -4.7537340e-03,
       -9.6035507e-03,  5.0072931e-03, -8.7595852e-03, -4.3918253e-03,
       -3.5099984e-05, -2.9618145e-04, -7.6612402e-03,  9.6147433e-03,
        4.9820580e-03,  9.2331432e-03, -8.1579173e-03,  4.4957981e-03,
       -4.1370760e-03,  8.2453608e-04,  8.4986202e-03, -4.4621765e-03,
        4.5175003e-03, -6.7869602e-03, -3.5484887e-03,  9.3985079e-03,
       -1.5776526e-03,  3.2137157e-04, -4.1406299e-03, -7.6826881e-03,
       -1.5080082e-03,  2.4697948e-03, -8.8802696e-04,  5.5336617e-03,
       -2.7429771e-03,  2.2600652e-03,  5.4557943e-03,  8.3459532e-03,
       -1.4537406e-03, -9.2081428e-03,  4.3705525e-03,  5.7178497e-04,
        7.4419081e-03, -8.1328274e-04, -2.6384138e-03, -8.7530091e-03,
       -8.5655687e-04,  2.8265631e-03,  5.4014288e-03,  7.0526563e-03,
       -5.7031214e-03,  1.8588197e-03,  6.0888636e-03, -4.7980510e-03,
       -3.1072604e-03,  6.7976294e-03,  1.6314756e-03,  1.8991709e-04,
        3.4736372e-03,  2.1777749e-04,  9.6188262e-03,  5.0606038e-03,
       -8.9173904e-03, -7.0415605e-03,  9.0145587e-04,  6.3925339e-03],
      dtype=float32)

In [20]:
#Checking the similar words
word2vec_model.wv.most_similar("phone")

[('drain', 0.2188439965248108),
 ('happy', 0.21615555882453918),
 ('buy', 0.09311048686504364),
 ('wwwshopcom', 0.09291722625494003),
 ('loved', 0.08404714614152908),
 ('quality', 0.07964139431715012),
 ('really', 0.06437788903713226),
 ('amazing', 0.06283695995807648),
 ('2', 0.05433367192745209),
 ('purchase', 0.02706480585038662)]

## 3.2 Creating One vector for each review

In [26]:
def review_vector(review):
    words=review.split()

    word_vectors=[]

    for word in words:
        if word in word2vec_model.wv:
            word_vectors.append(word2vec_model.wv[word])

    if len(word_vectors)==0:
        return np.zeros(100)

    return np.mean(word_vectors,axis=0)

## 3.3 Converting all reviews into Word2Vec Vectors

In [27]:
X_word2vec = np.array([review_vector(review) for review  in df["clean_review"]])

X_word2vec

array([[-1.1108494e-03,  4.1669486e-03,  1.7939175e-03,  5.0822902e-03,
        -5.4089725e-04,  1.0162356e-03,  1.2805077e-03,  2.9042761e-03,
        -1.9860307e-04, -1.5174150e-03,  2.9412019e-03, -2.4230212e-04,
         3.7189948e-03,  1.8357991e-03,  1.9347767e-03, -1.8793595e-03,
         4.8274691e-03,  9.1992458e-04, -6.2403106e-03, -1.1510784e-03,
        -1.3682539e-04, -5.7112670e-04,  2.8514987e-04, -1.3549546e-04,
         5.4760062e-04,  4.3914065e-04,  7.1083481e-04,  1.6252795e-03,
        -1.4631439e-03,  1.9826954e-03,  1.5096038e-03, -5.1674345e-03,
         5.9080136e-04, -3.3107197e-03, -1.8429131e-03,  1.3930362e-03,
         2.3377431e-03, -9.3135273e-04, -1.7040556e-04,  6.5855467e-04,
        -4.7365722e-04,  1.9578878e-03, -1.9794551e-03,  1.9753794e-03,
        -3.5023206e-04, -7.4159885e-07, -8.3115959e-04, -1.9547825e-03,
        -4.3561126e-04,  1.9971260e-03,  1.2390589e-03, -1.9059574e-03,
        -5.7090558e-03, -2.6510786e-03, -2.1207121e-03,  6.1321509e-04,
         3.1306918e-03,  5.3869176e-04, -1.7488028e-03, -4.9134297e-04,
        -1.4315152e-03,  1.5588450e-03,  8.1049727e-04, -2.2432182e-03,
        -1.4986338e-03,  3.8524696e-03,  1.9745254e-03,  1.4926248e-03,
        -1.2868473e-03, -8.7003355e-05,  2.4042821e-03,  1.2981725e-03,
         5.0582655e-04, -7.0128721e-05,  1.8347125e-04,  3.5364414e-04,
         1.9613118e-03,  3.2588691e-03, -1.2612086e-03, -8.8257715e-04,
        -4.6730977e-03, -6.3572610e-05,  1.8631710e-03,  3.2077736e-04,
        -1.5745265e-03, -1.2869916e-04,  2.2812963e-03, -3.8786004e-03,
        -6.5176986e-04, -3.2789534e-04, -1.0053259e-03,  4.5871428e-05,
         8.7654282e-04,  2.5709425e-05,  2.2594242e-03, -1.8179054e-04,
        -4.3494601e-04, -2.3675084e-04, -1.8115713e-03,  1.2361200e-03],
       [ 1.6201957e-04,  9.3603070e-04,  4.7750870e-04, -1.1036007e-03,
         2.4425024e-03, -1.9077243e-03,  1.7992148e-04,  4.4864500e-03,
        -1.3425694e-03, -1.7577178e-03, -1.9419739e-03, -4.6636709e-03,
        -2.3223853e-03,  1.3431939e-03, -1.7709979e-05, -8.2016370e-04,
         1.5178191e-03,  3.0856379e-03,  1.3365381e-03, -4.0366165e-03,
         3.1748172e-03,  1.1157960e-03, -2.1158809e-04, -5.9650507e-04,
         1.3487220e-03,  1.6857622e-03, -1.8007201e-03,  9.8426931e-04,
        -2.2533935e-04, -2.9443006e-04, -7.0909061e-04, -1.2757446e-03,
         4.2987123e-04, -2.6123056e-03, -1.4062875e-03, -8.1898156e-04,
         7.8472798e-04,  9.6369040e-04, -7.7171651e-05, -1.4534370e-03,
         2.7780270e-04, -1.9853220e-03,  5.8263049e-05,  3.8947223e-03,
         5.9240469e-04,  1.7362853e-04, -3.4653884e-03, -2.1896602e-03,
         2.4347450e-03,  8.7707385e-04, -5.3239416e-04, -8.0869003e-04,
         3.9848918e-04, -1.3501010e-03,  9.8040036e-04, -1.2036545e-04,
         1.9830640e-03, -1.4410350e-03,  8.4512180e-04,  4.0946696e-03,
        -8.0583181e-04, -4.3291540e-04,  2.0229344e-03,  2.5311424e-03,
         7.2835479e-04,  2.9147181e-03,  2.0104731e-03,  4.4798460e-03,
         2.6369593e-04,  1.3284306e-03,  1.8232547e-03,  4.3544266e-04,
         2.3924627e-03, -5.9066311e-04,  3.6282341e-03,  1.4858579e-03,
         4.6585528e-03,  6.9069926e-04, -2.5926784e-04, -2.0987010e-03,
        -3.6424708e-03, -6.4637937e-04, -1.6383087e-04,  1.6544473e-03,
         1.6211522e-04,  1.3472227e-03,  2.4854562e-03, -1.3124150e-03,
         8.2075654e-04, -8.8224176e-04,  3.9280993e-03,  2.2303183e-03,
         4.4516362e-03, -2.9802820e-04,  1.7367312e-03,  2.7372946e-03,
         1.4875960e-03,  7.6435931e-04,  1.1363900e-03,  3.4174290e-03],
       [-9.3803211e-04,  2.4854434e-03,  2.7987952e-03,  3.5973191e-03,
         8.1227487e-04, -3.8555029e-03,  1.1922097e-03,  3.0324515e-03,
        -2.9198334e-03, -4.5769075e-03,  3.8560035e-03, -1.9251198e-03,
         2.5303683e-03, -1.6959178e-03,  4.0207999e-03,  2.2999702e-03,
         2.4612187e-03, -2.7289703e-03, -2.9658612e-03, -4.2244960e-03,
        -1.9618498e-04,  3.8988789e-04,  4.6107345e-03, -4.3035788e-03,
        -2.2705069e-03,  8.7763276e-04, -2.8477765e-03,  2.5199784e-03,
         4.4943465e-04,  9.9449209e-04,  1.7368282e-03, -1.8676863e-03,
         1.5339720e-03,  1.8283975e-03,  3.4671914e-04,  3.6779430e-03,
         2.0125054e-03,  1.2228425e-03, -2.3095713e-03,  1.5665956e-03,
         1.7913105e-03,  5.2115379e-04, -1.6554988e-03,  1.3476639e-03,
         4.0774871e-04, -5.5626465e-04,  8.5572439e-04,  2.7523728e-04,
        -3.7241780e-04,  1.9315963e-03,  4.7054634e-04, -1.3022700e-03,
        -3.7807453e-04, -5.7011336e-04, -1.1712870e-03,  1.0002514e-03,
        -6.2953733e-04,  3.1447646e-03,  3.1103326e-03,  4.7072969e-04,
        -2.3894708e-03,  8.7318424e-04,  3.0550465e-03, -1.4749329e-04,
        -2.8628774e-03,  1.7800903e-03, -1.8347997e-03,  1.3193821e-03,
        -1.3723950e-03, -1.6129139e-03, -2.3690976e-04,  1.7492011e-03,
         1.4558799e-03,  3.7105179e-03, -1.3085583e-03, -7.8443025e-04,
        -1.2054117e-03, -1.9233344e-03, -8.6590898e-04, -1.2943832e-03,
        -2.1626560e-03,  2.5601906e-03,  8.0281484e-04,  1.9409031e-03,
         8.1952382e-04, -1.0395211e-03, -6.2087772e-04, -5.6221936e-04,
         4.0370165e-03,  6.5596873e-04, -8.6488493e-04,  1.8815191e-04,
        -1.4905671e-03,  1.6182262e-03,  3.7463561e-03, -4.2781187e-04,
         6.3144590e-04, -1.4102320e-03,  8.8747346e-04, -2.5450527e-03],
       [-2.0676134e-03, -2.1242769e-04, -1.0038171e-03, -3.8701721e-04,
        -3.8007256e-03, -3.8655649e-04,  4.5508314e-03,  3.6898800e-03,
        -4.7176192e-03, -1.2304586e-03,  4.9283740e-04,  5.8525061e-04,
        -5.1827841e-03,  2.0801125e-03, -4.3755313e-03, -3.8162391e-03,
         7.2603277e-04,  1.9313953e-03, -8.3202391e-04, -6.2532560e-03,
         6.9211179e-05, -1.6122427e-03,  8.0220606e-03,  4.7301287e-03,
        -5.2687241e-04, -9.6639100e-04,  2.7069895e-04, -8.3097443e-04,
        -3.6047120e-03,  2.8965948e-04,  2.9262982e-03,  3.6965340e-04,
         1.3677242e-03, -5.4511167e-03,  2.1724962e-05,  6.9027266e-04,
         1.0330342e-03, -1.5159568e-03, -3.9165129e-04, -3.8854587e-03,
         2.2520549e-03, -3.7375155e-03, -4.3696081e-03, -1.2150437e-03,
         2.2015171e-03, -1.8755335e-04, -3.1589479e-03,  1.8411432e-03,
         1.1772846e-03, -5.4871768e-04, -4.1446346e-04, -2.0868550e-03,
         1.2646348e-03,  1.9217777e-03, -2.6702844e-03, -4.6006422e-03,
         5.9604412e-04, -8.0412067e-03, -4.6487027e-03, -3.3106124e-03,
         2.8416675e-03, -2.7720723e-03,  3.5375347e-03, -3.3935767e-03,
        -1.1246384e-03,  2.5586465e-03,  9.5513160e-04,  3.0877637e-03,
        -5.4703522e-03, -5.8796536e-04,  8.9819427e-05,  6.7287432e-03,
         1.6608421e-04,  1.2196177e-03,  3.3787212e-03,  2.0786761e-03,
         7.4139971e-05,  4.3737162e-03,  5.6582340e-04, -1.9545974e-03,
         1.1617241e-03, -4.4949967e-03,  1.7861538e-03, -6.8133307e-04,
        -3.7652298e-03, -5.2558272e-03,  4.6996451e-03,  3.3787941e-04,
        -5.2119093e-03,  1.1998634e-03,  2.7845162e-03,  1.2148110e-03,
        -7.4785319e-04, -1.8618270e-03,  5.3596529e-03,  7.3554204e-04,
         9.7480649e-04, -4.1628503e-03,  7.4765924e-04,  2.0754228e-03]],
      dtype=float32)

In [29]:
X_word2vec.shape

(4, 100)

In [30]:
word2vec_df = pd.DataFrame(X_word2vec)

word2vec_df.round(3)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.001,0.004,0.002,0.005,-0.001,0.001,0.001,0.003,-0.000,-0.002,...,-0.001,0.000,0.001,0.000,0.002,-0.000,-0.000,-0.000,-0.002,0.001
1,0.000,0.001,0.000,-0.001,0.002,-0.002,0.000,0.004,-0.001,-0.002,...,0.004,0.002,0.004,-0.000,0.002,0.003,0.001,0.001,0.001,0.003
2,-0.001,0.002,0.003,0.004,0.001,-0.004,0.001,0.003,-0.003,-0.005,...,-0.001,0.000,-0.001,0.002,0.004,-0.000,0.001,-0.001,0.001,-0.003
3,-0.002,-0.000,-0.001,-0.000,-0.004,-0.000,0.005,0.004,-0.005,-0.001,...,0.003,0.001,-0.001,-0.002,0.005,0.001,0.001,-0.004,0.001,0.002

## 4.Model Building | 5.Model Training

In [31]:
from sklearn.linear_model import LogisticRegression

X_w2v=X_word2vec
y=df["sentiment"]

word2vec_model_classifier = LogisticRegression()
word2vec_model_classifier.fit(X_w2v,y)

LogisticRegression()

## 6.Model Testing

In [33]:
new_review =["Good Camera and battery"]

new_review_clean = [preprocess(text) for text in new_review]

new_review_word2vec = np.array([review_vector(review) for review in new_review_clean])

prediction_word2vec=word2vec_model_classifier.predict(new_review_word2vec)

print(prediction_word2vec)

['Positive']